// Package theme holds the house color palettes that agent-deck offers in
// addition to the two built-in Tokyo Night schemes ("dark" and "light").
//
// It is a leaf package on purpose: internal/ui, internal/session and
// internal/tmux all need to agree on which theme names are valid and what
// chrome a theme wants, and none of them can import each other. Colors are
// stored as "#rrggbb" strings so tmux can use them verbatim and the UI can
// wrap them in lipgloss.Color.
//
// Palette provenance lives in ~/cloud/sync/design/palettes — a value that is
// not in the source palette is marked "derived" with the derivation.
package theme

// Palette is one named color scheme. The thirteen color roles mirror the
// built-in dark/light structs in internal/ui/styles.go; the Tmux* fields
// describe the chrome agent-deck paints onto its tmux sessions.
type Palette struct {
	Name    string // config value, e.g. "wildcherry"
	Display string // settings-panel label, e.g. "Wild Cherry"
	Light   bool   // true for light-background palettes

	// WIP marks a palette whose source is still being revised upstream of
	// agent-deck. Note is shown under the theme picker when it is selected,
	// so the deck says out loud that these colors may move.
	WIP  bool
	Note string

	Bg      string
	Surface string
	Border  string
	Text    string
	TextDim string
	Accent  string
	Purple  string
	Cyan    string
	Green   string
	Yellow  string
	Orange  string
	Red     string
	Comment string

	// Glaze is the pack's enamel: the colour that makes a Kettle glaze pack
	// recognisably itself. It is CHROME ONLY — never text. A body-voiced glaze
	// (Cerise cherry, Nectar amber, Artichaut green) sits on a hue that
	// collides with a status signal (red / yellow / green), so painting words
	// with it would make ordinary titles read as alarms. The deck spends it on
	// transient or one-cell fields only — currently just the selection bead —
	// per the design law: "the enamel fills a field only where the field is
	// transient or small (cursor, bead, dot); a persistent field is a shade."
	//
	// Empty means "unset — wear the Accent". Read it through GlazeColor(),
	// never directly, so the fallback is never skipped for a pack the
	// generator emits without an enamel. There is deliberately no
	// OnGlaze: nothing in the deck draws text on the glaze, because the glaze
	// never becomes a background.
	Glaze string

	// TmuxWindowStyle is the tmux window-style value. "default" lets the
	// terminal's own background (and any transparency or blur it applies)
	// show through the pane; an explicit "bg=#rrggbb" paints over it.
	TmuxWindowStyle string
	TmuxStatusBg    string
	TmuxStatusFg    string
	TmuxHint        string
}

// palettes is the house registry. Built-in "dark"/"light" are NOT here —
// they stay in internal/ui/styles.go so upstream owns them.
var palettes = map[string]Palette{
	// Wild Cherry — the Ghostty colorscheme avicenna runs, so the deck and
	// the terminal underneath it read as one surface. Values taken from
	// ~/.config/ghostty/config (Charles's in-use variant, which differs
	// slightly from Ghostty's shipped "Wild Cherry" theme file).
	"wildcherry": {
		Name:    "wildcherry",
		Display: "Wild Cherry",

		Bg:      "#1f1626", // ghostty background
		Surface: "#2c2433", // derived: bg mixed 6% toward white
		Border:  "#3c2059", // derived: bg mixed 28% toward palette 4 (#883bdc)
		Text:    "#d9faff", // ghostty foreground
		TextDim: "#85939d", // derived: fg mixed 45% toward bg
		Accent:  "#d93f85", // palette 1 — the cherry; selection + titles
		Purple:  "#883bdc", // palette 4
		Cyan:    "#009cc9", // palette 8
		Green:   "#2ab250", // palette 2
		Yellow:  "#ffd16e", // palette 3
		Orange:  "#eac066", // palette 11
		Red:     "#ff919d", // palette 14 — brightest red-family, reads as alarm
		Comment: "#85939d", // = TextDim
		Glaze:   "#d93f85", // = Accent: wildcherry has no separate enamel

		TmuxWindowStyle: "default", // keep Ghostty's opacity/blur intact
		TmuxStatusBg:    "#2c2433",
		TmuxStatusFg:    "#d9faff",
		TmuxHint:        "#85939d",
	},

	// >>> kettle family — generated by design/palettes/scripts/kettle-promote.py; do not hand-edit
	// Kettle — the product palette, dark. Source: design/palettes/library/kettle.json (modes.dark.roles).
	"kettle": {
		Name:    "kettle",
		Display: "Kettle",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4e", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#8a8a92", // role muted
		Accent:  "#c8a24a", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#8a8a92", // = TextDim
		Glaze:   "#c8a24a", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#8a8a92",
	},

	// Kettle Light — same palette, light mode (modes.light.roles).
	"kettle-light": {
		Name:    "kettle-light",
		Display: "Kettle Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bcbdc6", // role line
		Text:    "#181a23", // role ink
		TextDim: "#5b5d66", // role muted
		Accent:  "#1b4979", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006276", // role cyan
		Green:   "#00591a", // role good
		Yellow:  "#855100", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5b5d66", // = TextDim
		Glaze:   "#1b4979", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#181a23",
		TmuxHint:        "#5b5d66",
	},

	// Kettle Cerise — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-cerise": {
		Name:    "kettle-cerise",
		Display: "Cerise",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4c", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#898991", // role muted
		Accent:  "#7d9fc7", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#898991", // = TextDim
		Glaze:   "#ca363a", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#898991",
	},

	// Kettle Cerise Light — glaze pack, light mode.
	"kettle-cerise-light": {
		Name:    "kettle-cerise-light",
		Display: "Cerise Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bbbdc7", // role line
		Text:    "#1a1a1e", // role ink
		TextDim: "#5f5f64", // role muted
		Accent:  "#1b4979", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5f5f64", // = TextDim
		Glaze:   "#ca363a", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#1a1a1e",
		TmuxHint:        "#5f5f64",
	},

	// Kettle Nectar — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-nectar": {
		Name:    "kettle-nectar",
		Display: "Nectar",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4c", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#898991", // role muted
		Accent:  "#7d9fc7", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#898991", // = TextDim
		Glaze:   "#f7a224", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#898991",
	},

	// Kettle Nectar Light — glaze pack, light mode.
	"kettle-nectar-light": {
		Name:    "kettle-nectar-light",
		Display: "Nectar Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bbbdc7", // role line
		Text:    "#1a1a1e", // role ink
		TextDim: "#5f5f64", // role muted
		Accent:  "#1b4979", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5f5f64", // = TextDim
		Glaze:   "#f7a224", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#1a1a1e",
		TmuxHint:        "#5f5f64",
	},

	// Kettle Artichaut — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-artichaut": {
		Name:    "kettle-artichaut",
		Display: "Artichaut",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4c", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#898991", // role muted
		Accent:  "#7d9fc7", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#898991", // = TextDim
		Glaze:   "#709841", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#898991",
	},

	// Kettle Artichaut Light — glaze pack, light mode.
	"kettle-artichaut-light": {
		Name:    "kettle-artichaut-light",
		Display: "Artichaut Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bbbdc7", // role line
		Text:    "#1a1a1e", // role ink
		TextDim: "#5f5f64", // role muted
		Accent:  "#1b4979", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5f5f64", // = TextDim
		Glaze:   "#709841", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#1a1a1e",
		TmuxHint:        "#5f5f64",
	},

	// Kettle Marseille — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-marseille": {
		Name:    "kettle-marseille",
		Display: "Marseille",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4c", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#898991", // role muted
		Accent:  "#2b8fd7", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#898991", // = TextDim
		Glaze:   "#3899e2", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#898991",
	},

	// Kettle Marseille Light — glaze pack, light mode.
	"kettle-marseille-light": {
		Name:    "kettle-marseille-light",
		Display: "Marseille Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bbbdc7", // role line
		Text:    "#1a1a1e", // role ink
		TextDim: "#5f5f64", // role muted
		Accent:  "#00639e", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5f5f64", // = TextDim
		Glaze:   "#3899e2", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#1a1a1e",
		TmuxHint:        "#5f5f64",
	},

	// Kettle Cobalt — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-cobalt": {
		Name:    "kettle-cobalt",
		Display: "Cobalt",

		Bg:      "#16161e", // role ground
		Surface: "#1c1c24", // role panel (ground +1 shade step)
		Border:  "#3f3f4c", // role line
		Text:    "#d8d8e0", // role ink
		TextDim: "#898991", // role muted
		Accent:  "#4d83ff", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#898991", // = TextDim
		Glaze:   "#2a5cda", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#1c1c24",
		TmuxStatusFg:    "#d8d8e0",
		TmuxHint:        "#898991",
	},

	// Kettle Cobalt Light — glaze pack, light mode.
	"kettle-cobalt-light": {
		Name:    "kettle-cobalt-light",
		Display: "Cobalt Light",
		Light:   true,

		Bg:      "#dfe1e8", // role ground
		Surface: "#e7e9ee", // role panel (ground +1 shade step)
		Border:  "#bbbdc7", // role line
		Text:    "#1a1a1e", // role ink
		TextDim: "#5f5f64", // role muted
		Accent:  "#2455d2", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5f5f64", // = TextDim
		Glaze:   "#2a5cda", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dfe1e8",
		TmuxStatusBg:    "#e7e9ee",
		TmuxStatusFg:    "#1a1a1e",
		TmuxHint:        "#5f5f64",
	},

	// Kettle Graphite — glaze pack, dark. Source: design/palettes/library/kettle-glazes.json.
	"kettle-graphite": {
		Name:    "kettle-graphite",
		Display: "Graphite",

		Bg:      "#121720", // role ground
		Surface: "#181d26", // role panel (ground +1 shade step)
		Border:  "#384150", // role line
		Text:    "#d4d9e3", // role ink
		TextDim: "#848a93", // role muted
		Accent:  "#748bab", // role accent
		Purple:  "#9f7bc7", // role magenta
		Cyan:    "#389bb4", // role cyan
		Green:   "#7dba6f", // role good
		Yellow:  "#ddbb70", // role yellow_bright
		Orange:  "#e79187", // role red_bright
		Red:     "#d4756b", // role warn
		Comment: "#848a93", // = TextDim
		Glaze:   "#5c7392", // chrome only (bead); never text

		TmuxWindowStyle: "default",
		TmuxStatusBg:    "#181d26",
		TmuxStatusFg:    "#d4d9e3",
		TmuxHint:        "#848a93",
	},

	// Kettle Graphite Light — glaze pack, light mode.
	"kettle-graphite-light": {
		Name:    "kettle-graphite-light",
		Display: "Graphite Light",
		Light:   true,

		Bg:      "#dce2e9", // role ground
		Surface: "#e5eaef", // role panel (ground +1 shade step)
		Border:  "#b7bec9", // role line
		Text:    "#181b1f", // role ink
		TextDim: "#5c6065", // role muted
		Accent:  "#4b617f", // role accent
		Purple:  "#633f81", // role magenta
		Cyan:    "#006071", // role cyan
		Green:   "#00581f", // role good
		Yellow:  "#7c5500", // role gold
		Orange:  "#b23a26", // role red_bright
		Red:     "#8e1904", // role warn
		Comment: "#5c6065", // = TextDim
		Glaze:   "#5c7392", // chrome only (bead); never text

		TmuxWindowStyle: "bg=#dce2e9",
		TmuxStatusBg:    "#e5eaef",
		TmuxStatusFg:    "#181b1f",
		TmuxHint:        "#5c6065",
	},
	// <<< kettle family
}

// GlazeColor returns the chrome-only enamel colour for this palette, falling
// back to Accent when the palette does not declare one. Always non-empty for a
// well-formed palette, so callers can hand it straight to lipgloss.
//
// Call this rather than reading Glaze. Every registered palette declares one
// today, but the kettle block is generated: a future run of kettle-promote.py
// may omit the field for a pack that has no enamel of its own, and the correct
// reading of an omission is "wear the Accent", not "wear nothing".
func (p Palette) GlazeColor() string {
	if p.Glaze == "" {
		return p.Accent
	}
	return p.Glaze
}

// Get returns the house palette registered under name.
func Get(name string) (Palette, bool) {
	p, ok := palettes[name]
	return p, ok
}

// IsHouse reports whether name is a house theme (as opposed to the built-in
// "dark"/"light"/"system" values, or garbage).
func IsHouse(name string) bool {
	_, ok := palettes[name]
	return ok
}

// order is the display order of the house themes in the picker: the terminal
// scheme avicenna actually runs first, then the product palette and its light
// variant. Every key in palettes must appear here (asserted by the tests).
var order = []string{"wildcherry", "kettle", "kettle-light", "kettle-cerise", "kettle-cerise-light", "kettle-nectar", "kettle-nectar-light", "kettle-artichaut", "kettle-artichaut-light", "kettle-marseille", "kettle-marseille-light", "kettle-cobalt", "kettle-cobalt-light", "kettle-graphite", "kettle-graphite-light"}

// Names returns the house theme config values in display order.
func Names() []string {
	out := make([]string, 0, len(order))
	for _, name := range order {
		if _, ok := palettes[name]; ok {
			out = append(out, name)
		}
	}
	return out
}

// All returns the house palettes in Names() order.
func All() []Palette {
	names := Names()
	out := make([]Palette, 0, len(names))
	for _, name := range names {
		out = append(out, palettes[name])
	}
	return out
}
